apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sara-api
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/cmoreira-dev/gitops.local-sara.git
    targetRevision: main
    path: helm/api
  destination:
    server: https://kubernetes.default.svc
    namespace: sara
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
